name: CI workflow
on:
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  test-python:
    runs-on: ubuntu-latest
    container: python:3.9-slim
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt
      - name: Lint with flake8
        run: |
          flake8 server --count --select=E9,F63,F7,F82 --show-source --statistics
          flake8 server --count --max-complexity=10 --max-line-length=127 --statistics
      - name: Run unit tests with nose
        run: nosetests
  test-js:
    runs-on: ubuntu-latest
    container: node:slim
    steps:
      - name: Checkout
        uses: actions/checkout@v1
      - name: Install Dependencies
        run: npm install
      - name: Lint with ESLint
        run: npm run lint
      - name: Run unit tests with jest
        run: npm test
        
